image: maven:3.3.3-jdk-8
stages:
  - build
  - test
  - deploy
build_job:
  stage: build
  script:
    - mvn --batch-mode compile -Dmaven.test.skip=true -Djacoco.skip=true
#test_sonar_preview_job:
#  stage: test
#  except:
#    - master
#  script:
#    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=incremental
test_sonar_job:
  stage: test
#  only:
#    - master
  script:
    - apt-get update
    - apt-get install -y xvfb firefox
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.jdbc.url=$SONAR_DB -Dsonar.jdbc.username=$SONAR_USERNAME -Dsonar.jdbc.password=$SONAR_PASSWORD
deploy_job:
  stage: deploy
  only:
    - master
  script:
    - mvn --batch-mode deploy -Dmaven.test.skip=true -Djacoco.skip=true